# Generated by Django 4.1.1 on 2022-09-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='topic',
        ),
    ]
