# Generated by Django 4.1.1 on 2022-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
