# Generated by Django 4.1.1 on 2022-10-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(default='Light', max_length=30),
        ),
    ]
