# Generated by Django 4.1.1 on 2022-10-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_account_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='theme',
            field=models.CharField(default='light', max_length=30),
        ),
    ]
