# Generated by Django 4.1.1 on 2022-09-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
