# Generated by Django 4.1.1 on 2022-09-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='America/Chicago', max_length=50),
        ),
    ]
