# Generated by Django 4.1.1 on 2022-09-24 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bedtime',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wake_up_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
